#!/bin/env python
import argparse
import sys
parser = argparse.ArgumentParser()
parser.add_argument("-n","--number",help="number of blank lines",default=1, nargs=1)
args= parser.parse_args()


for line in sys.stdin.readlines():
    print(line.strip())
    for i in range(int(args.number[0])):
        print
    
